pipeline {
    agent any

    environment {
        APP_NAME = 'toy'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Login & Build') {
            steps {
                withCredentials([
                        string(credentialsId: 'dockerhub-username', variable: 'DOCKER_USERNAME'),
                        string(credentialsId: 'docker-hub-password', variable: 'DOCKER_PASSWORD')
                ]) {
                    script {
                        def imageTag = "${DOCKER_USERNAME}/${APP_NAME}:latest"
                        sh '''
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                        docker build -t ''' + imageTag + ''' -f infra/Dockerfile .
                        '''
                    }
                }
            }
        }

        stage('Docker Push (only if PR to main)') {
            when {
                expression {
                    return env.CHANGE_ID && env.CHANGE_TARGET == 'main'
                }
            }
            steps {
                script {
                    def imageTag = "${DOCKER_USERNAME}/${APP_NAME}:latest"
                    sh '''
                    docker push ''' + imageTag + '''
                    '''
                }
            }
        }
    }
}
