spring:
  application:
    name: toy
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hibernate.default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  devtools:
    restart:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-mills: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration-mills: ${JWT_REFRESH_EXPIRATION}

mail:
  verification-url-prefix: https://toy.kimnow.site/api/v1/auth/verify?token=

auth:
  redirect-url:
    success: https://toy.kimnow.site/login
    fail: https://toy.kimnow.site/verify-failed
